apiVersion: 1
datasources:
  - orgId: 1
    version: 3
    name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: K1XkGKR4z
  - orgId: 1
    version: 1
    name: LocalInflux
    type: influxdb
    access: proxy
    database: inspectit
    url: http://influxdb:8086