apiVersion: 1
datasources:
  - orgId: 1
    version: 3
    name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: K1XkGKR4z
  - orgId: 1
    version: 1
    name: LocalPrometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
    secureJsonData:
      tlsCACert: $LOCALPROMETHEUS_TLSCACERT
      tlsClientCert: $LOCALPROMETHEUS_TLSCLIENTCERT
      tlsClientKey: $LOCALPROMETHEUS_TLSCLIENTKEY
